// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAccounting.Data;

#nullable disable

namespace MvcTest.Migrations
{
    [DbContext(typeof(SqlDBContext))]
    [Migration("20251107065501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("MyAccounting.Data.Model.CurrencyUnit", b =>
                {
                    b.Property<Guid>("CurrencyUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDesimal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CurrencyUnitID");

                    b.ToTable("CurrencyUnit");

                    b.HasData(
                        new
                        {
                            CurrencyUnitID = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDesimal = false,
                            Name = "ریال"
                        },
                        new
                        {
                            CurrencyUnitID = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsDesimal = false,
                            Name = "تومان"
                        });
                });

            modelBuilder.Entity("MyAccounting.Data.Model.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankCard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankShaba")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrencyUnitID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPerson")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonMobile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonTell")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.HasIndex("CurrencyUnitID");

                    b.HasIndex("UserID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.SettingKey", b =>
                {
                    b.Property<Guid>("SettingKeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingKeyID");

                    b.HasIndex("UserID");

                    b.ToTable("SettingKey");

                    b.HasData(
                        new
                        {
                            SettingKeyID = new Guid("11111111-1111-1111-1111-111111111111"),
                            Key = "NewTrasactionDateType"
                        });
                });

            modelBuilder.Entity("MyAccounting.Data.Model.SettingValue", b =>
                {
                    b.Property<Guid>("SettingValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SettingKeyID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SettingValueID");

                    b.HasIndex("SettingKeyID");

                    b.HasIndex("UserID");

                    b.ToTable("SettingValue");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PayerPersonID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReceiverPersonID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionTypeID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionID");

                    b.HasIndex("PayerPersonID");

                    b.HasIndex("ReceiverPersonID");

                    b.HasIndex("TransactionTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.TransactionType", b =>
                {
                    b.Property<Guid>("TransactionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTransactionTypeID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionTypeID");

                    b.HasIndex("ParentTransactionTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("TransactionType");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "",
                            IsActive = true,
                            IsAdmin = true,
                            Password = "0130fd5601a7addede0fb3dfac1657353497fe54d9a54a7a83b82ef77e5e6212",
                            Salt1 = "bcfbf4a8-67fc-4db9-ba7e-908afb4de0f7",
                            Salt2 = "ddc46224-2fdc-4320-b821-f7f7c2e65bba",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MyAccounting.Data.Model.Person", b =>
                {
                    b.HasOne("MyAccounting.Data.Model.CurrencyUnit", "CurrencyUnit")
                        .WithMany("Persons")
                        .HasForeignKey("CurrencyUnitID");

                    b.HasOne("MyAccounting.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.SettingKey", b =>
                {
                    b.HasOne("MyAccounting.Data.Model.User", null)
                        .WithMany("SettingKeys")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.SettingValue", b =>
                {
                    b.HasOne("MyAccounting.Data.Model.SettingKey", "SettingKey")
                        .WithMany("SettingValues")
                        .HasForeignKey("SettingKeyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAccounting.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettingKey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.Transaction", b =>
                {
                    b.HasOne("MyAccounting.Data.Model.Person", "PayerPerson")
                        .WithMany("TransactionPayers")
                        .HasForeignKey("PayerPersonID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyAccounting.Data.Model.Person", "ReceiverPerson")
                        .WithMany("TransactionReceivers")
                        .HasForeignKey("ReceiverPersonID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyAccounting.Data.Model.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAccounting.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayerPerson");

                    b.Navigation("ReceiverPerson");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.TransactionType", b =>
                {
                    b.HasOne("MyAccounting.Data.Model.TransactionType", "ParentTransactionType")
                        .WithMany("TransactionTypes")
                        .HasForeignKey("ParentTransactionTypeID");

                    b.HasOne("MyAccounting.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.CurrencyUnit", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.Person", b =>
                {
                    b.Navigation("TransactionPayers");

                    b.Navigation("TransactionReceivers");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.SettingKey", b =>
                {
                    b.Navigation("SettingValues");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.TransactionType", b =>
                {
                    b.Navigation("TransactionTypes");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyAccounting.Data.Model.User", b =>
                {
                    b.Navigation("SettingKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
